/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: deadpool (https://sketchfab.com/lvlup)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diorama-of-cyberpunk-city-19032d140af645fda039f09de2d798ad
Title: Diorama of cyberpunk city.
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import cityScene from "../3d/city.glb";

const City=({  isRotating,
    setIsRotating,
    setCurrentStage,
    currentFocusPoint,
    ...props})=> {
  const { nodes, materials } = useGLTF(cityScene);
  return (
    <a.group  {...props}>
      <group position={[-3.119, -0.036, -2.088]}>
        <mesh
          
          
          geometry={nodes.Object_6.geometry}
          material={materials.Wall}
        />
        <mesh
          
          
          geometry={nodes.Object_7.geometry}
          material={materials.Metall_blue}
        />
        <mesh
          
          
          geometry={nodes.Object_8.geometry}
          material={materials.Grey_metal}
        />
        <mesh
          
          
          geometry={nodes.Object_9.geometry}
          material={materials.concrete}
        />
        <mesh
          
          
          geometry={nodes.Object_10.geometry}
          material={materials.window_light}
        />
        <mesh
          
          
          geometry={nodes.Object_11.geometry}
          material={materials.heart}
        />
      </group>
      <group position={[2, 2, 3]}>
        <mesh
          
          
          geometry={nodes.Object_17.geometry}
          material={materials.Wall}
        />
        <mesh
          
          
          geometry={nodes.Object_18.geometry}
          material={materials.Metall_blue}
        />
        <mesh
          
          
          geometry={nodes.Object_19.geometry}
          material={materials.concrete}
        />
        <mesh
          
          
          geometry={nodes.Object_20.geometry}
          material={materials.tungsten}
        />
        <mesh
          
          
          geometry={nodes.Object_21.geometry}
          material={materials.headlight}
        />
      </group>
      <group position={[-3, 1, 3]}>
        <mesh
          
          
          geometry={nodes.Object_23.geometry}
          material={materials.Wall_dark}
        />
        <mesh
          
          
          geometry={nodes.Object_24.geometry}
          material={materials.window_light}
        />
        <mesh
          
          
          geometry={nodes.Object_25.geometry}
          material={materials.tungsten}
        />
        <mesh
          
          
          geometry={nodes.Object_26.geometry}
          material={materials.Yellow}
        />
        <mesh
          
          
          geometry={nodes.Object_27.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-3.721, 5.766, -3.191]}>
        <mesh
          
          
          geometry={nodes.Object_45.geometry}
          material={materials.Grey_metal}
        />
        <mesh
          
          
          geometry={nodes.Object_46.geometry}
          material={materials.Pipe}
        />
        <mesh
          
          
          geometry={nodes.Object_48.geometry}
          material={materials.Pipe}
          position={[1.274, -0.587, -0.709]}
        />
        <mesh
          
          
          geometry={nodes.Object_50.geometry}
          material={materials.Grey_metal}
          position={[1.274, -0.587, -0.709]}
        />
      </group>
      <group position={[-3.721, 5.766, -2.013]}>
        <mesh
          
          
          geometry={nodes.Object_52.geometry}
          material={materials.Grey_metal}
        />
        <mesh
          
          
          geometry={nodes.Object_53.geometry}
          material={materials.Pipe}
        />
        <mesh
          
          
          geometry={nodes.Object_55.geometry}
          material={materials.Pipe}
          position={[1.274, -0.587, -0.709]}
        />
        <mesh
          
          
          geometry={nodes.Object_57.geometry}
          material={materials.Grey_metal}
          position={[1.274, -0.587, -0.709]}
        />
      </group>
      <group position={[-1, 4.64, 0.436]}>
        <mesh
          
          
          geometry={nodes.Object_87.geometry}
          material={materials.Yellow}
        />
        <mesh
          
          
          geometry={nodes.Object_88.geometry}
          material={materials.Grey_metal}
        />
        <mesh
          
          
          geometry={nodes.Object_89.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-0.444, 4.986, 0.234]}>
        <mesh
          
          
          geometry={nodes.Object_91.geometry}
          material={materials.heart}
        />
        <mesh
          
          
          geometry={nodes.Object_92.geometry}
          material={materials["heart.001"]}
        />
      </group>
      <group position={[1.236, 4.255, 1.768]}>
        <mesh
          
          
          geometry={nodes.Object_94.geometry}
          material={materials.Black}
        />
        <mesh
          
          
          geometry={nodes.Object_95.geometry}
          material={materials.material}
        />
      </group>
      <group position={[-1.237, 1.915, -0.824]}>
        <mesh
          
          
          geometry={nodes.Object_97.geometry}
          material={materials.Black}
        />
        <mesh
          
          
          geometry={nodes.Object_98.geometry}
          material={materials.tungsten}
        />
      </group>
      <group position={[-1.237, 1.915, -2.894]}>
        <mesh
          
          
          geometry={nodes.Object_100.geometry}
          material={materials.Black}
        />
        <mesh
          
          
          geometry={nodes.Object_101.geometry}
          material={materials.tungsten}
        />
      </group>
      <group position={[2.782, 3.257, -1.55]}>
        <mesh
          
          
          geometry={nodes.Object_103.geometry}
          material={materials.Pipe}
        />
        <mesh
          
          
          geometry={nodes.Object_104.geometry}
          material={materials.street_light}
        />
      </group>
      <group
        position={[3.459, 3.257, 1.457]}
        rotation={[Math.PI / 2, -1.101, Math.PI / 2]}
      >
        <mesh
          
          
          geometry={nodes.Object_106.geometry}
          material={materials.Pipe}
        />
        <mesh
          
          
          geometry={nodes.Object_107.geometry}
          material={materials.street_light}
        />
      </group>
      <group position={[1.384, 0.021, 0.82]} scale={0.621}>
        <mesh
          
          
          geometry={nodes.Object_117.geometry}
          material={materials.material_19}
        />
        <mesh
          
          
          geometry={nodes.Object_118.geometry}
          material={materials.Grey_metal}
        />
        <mesh
          
          
          geometry={nodes.Object_119.geometry}
          material={materials.Black_metal}
        />
        <mesh
          
          
          geometry={nodes.Object_120.geometry}
          material={materials.headlight}
        />
        <mesh
          
          
          geometry={nodes.Object_121.geometry}
          material={materials.backlight}
        />
        <mesh
          
          
          geometry={nodes.Object_122.geometry}
          material={materials.Rubber}
        />
        <mesh
          
          
          geometry={nodes.Object_123.geometry}
          material={materials.Wheels}
        />
        <mesh
          
          
          geometry={nodes.Object_124.geometry}
          material={materials.Window}
        />
        <mesh
          
          
          geometry={nodes.Object_125.geometry}
          material={materials.Black}
        />
        <mesh
          
          
          geometry={nodes.Object_126.geometry}
          material={materials.Yellow}
        />
        <mesh
          
          
          geometry={nodes.Object_127.geometry}
          material={materials.Blue}
        />
        <mesh
          
          
          geometry={nodes.Object_128.geometry}
          material={materials.material_25}
        />
      </group>
      <group position={[-1.762, 0.012, -3.419]}>
        <mesh
          
          
          geometry={nodes.Object_132.geometry}
          material={materials.material_25}
        />
        <mesh
          
          
          geometry={nodes.Object_133.geometry}
          material={materials.Black_metal}
        />
        <mesh
          
          
          geometry={nodes.Object_134.geometry}
          material={materials.tungsten}
        />
      </group>
      <group position={[2.784, 4.183, 3.25]} rotation={[0, 0.597, 0]}>
        <mesh
          
          
          geometry={nodes.Object_156.geometry}
          material={materials.material_25}
        />
        <mesh
          
          
          geometry={nodes.Object_158.geometry}
          material={materials.Pipe}
        />
      </group>
      <group
        position={[3.342, 4.183, 3.575]}
        rotation={[-Math.PI, 1.107, -Math.PI]}
      >
        <mesh
          
          
          geometry={nodes.Object_160.geometry}
          material={materials.material_25}
        />
        <mesh
          
          
          geometry={nodes.Object_162.geometry}
          material={materials.Pipe}
        />
      </group>
      <mesh
        
        
        geometry={nodes.Object_4.geometry}
        material={materials.street}
      />
      <mesh
        
        
        geometry={nodes.Object_13.geometry}
        material={materials.Black}
      />
      <mesh
        
        
        geometry={nodes.Object_15.geometry}
        material={materials.concrete}
      />
      <mesh
        
        
        geometry={nodes.Object_29.geometry}
        material={materials.Grey_metal}
        position={[-1.568, 0.184, 2.481]}
      />
      <mesh
        
        
        geometry={nodes.Object_31.geometry}
        material={materials.Grey_metal}
        position={[-1.568, 0.184, 2.481]}
      />
      <mesh
        
        
        geometry={nodes.Object_33.geometry}
        material={materials.Grey_metal}
        position={[-1.141, 0.791, 3.437]}
      />
      <mesh
        
        
        geometry={nodes.Object_35.geometry}
        material={materials.wood}
        position={[3.47, 0.036, -1.55]}
      />
      <mesh
        
        
        geometry={nodes.Object_37.geometry}
        material={materials.Black_metal}
        position={[4.375, 4.765, -1.573]}
      />
      <mesh
        
        
        geometry={nodes.Object_39.geometry}
        material={materials.Black_metal}
        position={[3.957, 4.765, -1.573]}
      />
      <mesh
        
        
        geometry={nodes.Object_41.geometry}
        material={materials.Black_metal}
        position={[3.027, 4.765, -1.573]}
      />
      <mesh
        
        
        geometry={nodes.Object_43.geometry}
        material={materials.Black_metal}
        position={[2.608, 4.765, -1.573]}
      />
      <mesh
        
        
        geometry={nodes.Object_59.geometry}
        material={materials.Pipe}
        position={[-1.967, 5.092, -0.537]}
      />
      <mesh
        
        
        geometry={nodes.Object_61.geometry}
        material={materials.Pipe}
        position={[3.584, 4.093, 2.539]}
      />
      <mesh
        
        
        geometry={nodes.Object_63.geometry}
        material={materials.Pipe}
        position={[3.301, 4.093, 2.539]}
      />
      <mesh
        
        
        geometry={nodes.Object_65.geometry}
        material={materials.Pipe}
        position={[3.004, 4.093, 2.539]}
      />
      <mesh
        
        
        geometry={nodes.Object_67.geometry}
        material={materials.Grey_metal}
        position={[1.261, 4.183, 3.263]}
      />
      <mesh
        
        
        geometry={nodes.Object_69.geometry}
        material={materials.Pipe}
        position={[1.261, 4.622, 2.921]}
      />
      <mesh
        
        
        geometry={nodes.Object_71.geometry}
        material={materials.Pipe}
        position={[3, 3.381, 2.132]}
      />
      <mesh
        
        
        geometry={nodes.Object_73.geometry}
        material={materials.Pipe}
        position={[1, 3.381, 2.132]}
      />
      <mesh
        
        
        geometry={nodes.Object_75.geometry}
        material={materials.Pipe}
        position={[3.963, 3.451, 3.02]}
      />
      <mesh
        
        
        geometry={nodes.Object_77.geometry}
        material={materials.Grey_metal}
        position={[2.77, 0.697, 2.139]}
      />
      <mesh
        
        
        geometry={nodes.Object_79.geometry}
        material={materials.Pipe}
        position={[-1.084, 3.021, 0.114]}
      />
      <mesh
        
        
        geometry={nodes.Object_81.geometry}
        material={materials.Pipe}
        position={[-1.09, 4.581, -0.02]}
      />
      <mesh
        
        
        geometry={nodes.Object_83.geometry}
        material={materials.Pipe}
        position={[-1.085, 4.581, -0.02]}
      />
      <mesh
        
        
        geometry={nodes.Object_85.geometry}
        material={materials.Pipe}
        position={[-2.229, 0.888, -0.292]}
      />
      <mesh
        
        
        geometry={nodes.Object_109.geometry}
        material={materials.Pink_light}
        position={[3.801, 1.715, 1.969]}
      />
      <mesh
        
        
        geometry={nodes.Object_111.geometry}
        material={materials.Black}
        position={[-2.837, 5.184, -3.572]}
      />
      <mesh
        
        
        geometry={nodes.Object_113.geometry}
        material={materials.Black_metal}
        position={[0.246, 3.369, 2]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        
        
        geometry={nodes.Object_115.geometry}
        material={materials.Black_metal}
        position={[-1, 4.838, -3.63]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        
        
        geometry={nodes.Object_130.geometry}
        material={materials.Blue}
        position={[3.665, 0, -2.601]}
      />
      <mesh
        
        
        geometry={nodes.Object_136.geometry}
        material={materials.Rubber}
        position={[3.438, -0.043, -3.298]}
      />
      <mesh
        
        
        geometry={nodes.Object_138.geometry}
        material={materials.Pipe}
        position={[1.746, 0.27, 0]}
      />
      <mesh
        
        
        geometry={nodes.Object_140.geometry}
        material={materials["Red.001"]}
        position={[3.601, -0.039, -2.11]}
      />
      <mesh
        
        
        geometry={nodes.Object_142.geometry}
        material={materials.concrete}
        position={[2.617, 0.064, -3.539]}
        rotation={[0, 0.663, 0]}
      />
      <mesh
        
        
        geometry={nodes.Object_144.geometry}
        material={materials.Wall}
        position={[3.741, 0.145, -1.433]}
        rotation={[0, 0.765, 0]}
      />
      <mesh
        
        
        geometry={nodes.Object_146.geometry}
        material={materials.Blue}
        position={[3.322, 0, -3.658]}
        rotation={[-Math.PI, 0.398, -Math.PI]} 
      />
      <mesh 
        
        
        geometry={nodes.Object_148.geometry}
        material={materials.concrete}
        position={[0.102, 0.078, -0.671]}
        rotation={[0, -0.535, 0]}
      />
      <mesh
        
        
        geometry={nodes.Object_150.geometry}
        material={materials.concrete}
        position={[-0.03, 0.078, -0.671]}
        rotation={[0, 0.792, 0]}
        scale={0.547}
      />
      <mesh
        
        
        geometry={nodes.Object_152.geometry}
        material={materials.concrete}
        position={[0.012, 0.078, -0.623]}
        rotation={[-Math.PI, -0.575, -Math.PI]}
        scale={0.808}
      />
      <mesh
        
        
        geometry={nodes.Object_154.geometry}
        material={materials.concrete}
        position={[0.06, 0.078, -0.718]}
        rotation={[0, -1.24, 0]}
        scale={0.442}
      />
      <mesh
        
        
        geometry={nodes.Object_164.geometry}
        material={materials.heart}
        position={[-0.453, 4.598, 0.237]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={1.159}
      />
      <mesh
        
        
        geometry={nodes.Object_166.geometry}
        material={materials.Black_metal}
        position={[2.475, 4.375, 1.743]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        
        
        geometry={nodes.Object_168.geometry}
        material={materials.heart}
        position={[-2.318, 1.486, -4]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.622}
      />
    </a.group>
  );
}

useGLTF.preload("/diorama_of_cyberpunk_city..glb");

export default City
